"""add_models_DAS2

Revision ID: 9527c610f837
Revises: b537bcec6f5f
Create Date: 2022-10-22 17:35:57.095481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9527c610f837'
down_revision = 'b537bcec6f5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
