"""empty message

Revision ID: c55f78173bc7
Revises: cab6b85d27c8
Create Date: 2022-10-22 18:05:31.966944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55f78173bc7'
down_revision = 'cab6b85d27c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
