"""add_column_test

Revision ID: cab6b85d27c8
Revises: 6dbfa8a98ca5
Create Date: 2022-10-22 18:01:49.810663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab6b85d27c8'
down_revision = '6dbfa8a98ca5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
